# Generated by Django 4.1.5 on 2023-01-12 19:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('personnel', '0005_alter_profile_avatar'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
